# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-16 23:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlenderSubtaskDefinition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('output_format', models.CharField(choices=[('JPG', 'jpg'), ('JPEG', 'jpeg'), ('BMP', 'bmp'), ('SGI', 'sgi'), ('RGB', 'rgb'), ('BW', 'bw'), ('PNG', 'PNG'), ('JP2', 'jp2'), ('JP2C', 'jp2c'), ('TGA', 'tga'), ('CIN', 'cin'), ('DPX', 'dpx'), ('HDR', 'hdr'), ('TIF', 'tif'), ('TIFF', 'tiff')], max_length=32)),
                ('scene_file', models.CharField(max_length=256)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='UploadReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=256)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='VerificationRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtask_id', models.CharField(max_length=128)),
                ('source_package_path', models.CharField(max_length=255, unique=True)),
                ('result_package_path', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='uploadreport',
            name='verification_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='upload_reports', to='conductor.VerificationRequest'),
        ),
        migrations.AddField(
            model_name='blendersubtaskdefinition',
            name='verification_request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='blender_subtask_definition', to='conductor.VerificationRequest'),
        ),
    ]
