# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-06 14:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=256)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='UploadRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=256, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='VerificationRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=128)),
                ('subtask_id', models.CharField(max_length=128)),
                ('src_code', models.CharField(blank=True, max_length=255, null=True)),
                ('extra_data', models.CharField(blank=True, max_length=255, null=True)),
                ('short_description', models.CharField(blank=True, max_length=255, null=True)),
                ('working_directory', models.CharField(blank=True, max_length=255, null=True)),
                ('performance', models.CharField(blank=True, max_length=255, null=True)),
                ('docker_images', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AddField(
            model_name='uploadrequest',
            name='verification_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upload_requests', to='conductor.VerificationRequest'),
        ),
        migrations.AddField(
            model_name='uploadreport',
            name='upload_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='upload_reports', to='conductor.UploadRequest'),
        ),
    ]
