# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-24 22:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conductor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationrequest',
            name='upload_acknowledged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='verificationrequest',
            name='upload_finished',
            field=models.BooleanField(default=False),
        ),
    ]
