# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-06-27 13:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conductor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blendersubtaskdefinition',
            name='output_format',
            field=models.CharField(choices=[('JPG', 'jpg'), ('PNG', 'png'), ('EXR', 'exr')], max_length=32),
        ),
    ]
