# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-06-18 22:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conductor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blendersubtaskdefinition',
            name='blender_crop_script',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
    ]
