# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-04 07:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conductor', '0003_verificationrequest_verification_deadline'),
    ]

    operations = [
        migrations.CreateModel(
            name='Frame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('blender_subtask_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frames', to='conductor.BlenderSubtaskDefinition')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='frame',
            unique_together=set([('blender_subtask_definition', 'number')]),
        ),
    ]
