# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-04 14:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conductor', '0005_blendersubtaskdefinition_blender_crop_script'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blendersubtaskdefinition',
            name='blender_crop_script',
            field=models.TextField(blank=True, null=True),
        ),
    ]
