# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-05 11:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conductor', '0006_auto_20180704_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blendersubtaskdefinition',
            name='output_format',
            field=models.IntegerField(),
        ),
    ]
