# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-09 15:26
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conductor', '0006_auto_20180704_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blendersubtaskdefinition',
            name='scene_file',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='uploadreport',
            name='path',
            field=models.TextField(validators=[django.core.validators.MaxLengthValidator(1000)]),
        ),
        migrations.AlterField(
            model_name='verificationrequest',
            name='result_package_path',
            field=models.TextField(unique=True, validators=[django.core.validators.MaxLengthValidator(1000)]),
        ),
        migrations.AlterField(
            model_name='verificationrequest',
            name='source_package_path',
            field=models.TextField(unique=True, validators=[django.core.validators.MaxLengthValidator(1000)]),
        ),
    ]
