# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-17 09:08
from __future__ import unicode_literals

from django.db import migrations, models


def transfer_created_at_field_from_blender_subtask_definition_to_verification_request(apps, _schema_editor):
    BlenderSubtaskDefinition = apps.get_model('conductor', 'BlenderSubtaskDefinition')
    VerificationRequest = apps.get_model('conductor', 'VerificationRequest')

    for blender_subtask_definition in BlenderSubtaskDefinition.objects.all():
        verification_request = VerificationRequest.objects.get(blender_subtask_definition=blender_subtask_definition)
        verification_request.created_at = blender_subtask_definition.created_at

        verification_request.full_clean()
        verification_request.save()


class Migration(migrations.Migration):

    dependencies = [
        ('conductor', '0007_auto_20180709_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
        migrations.RunPython(
            transfer_created_at_field_from_blender_subtask_definition_to_verification_request,
        ),
        migrations.RemoveField(
            model_name='blendersubtaskdefinition',
            name='created_at',
        ),
    ]
