# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-29 12:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conductor', '0008_auto_20180717_0908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationrequest',
            name='subtask_id',
            field=models.CharField(max_length=36),
        ),
    ]
