# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-19 21:53
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conductor', '0009_auto_20180829_1224'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultTransferRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtask_id', models.CharField(max_length=36)),
                ('result_package_path', models.TextField(validators=[django.core.validators.MaxLengthValidator(1000)])),
                ('upload_finished', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='uploadreport',
            name='result_transfer_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='upload_reports', to='conductor.ResultTransferRequest'),
        ),
    ]
