# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-11-07 12:26
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conductor', '0010_auto_20180919_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resulttransferrequest',
            name='result_package_path',
            field=models.TextField(unique=True, validators=[django.core.validators.MaxLengthValidator(1000)]),
        ),
        migrations.AlterField(
            model_name='resulttransferrequest',
            name='subtask_id',
            field=models.CharField(max_length=36, unique=True),
        ),
    ]
