# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-03-28 08:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conductor', '0012_auto_20181222_1926'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlenderCropScriptParameters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resolution_x', models.IntegerField()),
                ('resolution_y', models.IntegerField()),
                ('samples', models.IntegerField()),
                ('use_compositing', models.BooleanField()),
                ('borders_y_min', models.DecimalField(decimal_places=9, max_digits=10)),
                ('borders_y_max', models.DecimalField(decimal_places=9, max_digits=10)),
                ('borders_x_min', models.DecimalField(decimal_places=9, max_digits=10)),
                ('borders_x_max', models.DecimalField(decimal_places=9, max_digits=10)),
            ],
        ),
        migrations.AddField(
            model_name='blendersubtaskdefinition',
            name='blender_crop_script_parameters',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blender_subtask_definition', to='conductor.BlenderCropScriptParameters'),
        ),
    ]
