# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-21 16:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceiveOutOfBandStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Message')),
            ],
            options={
                'verbose_name': 'ReceiveOutOfBand status',
                'verbose_name_plural': 'ReceiveOutOfBand statuses',
            },
        ),
        migrations.CreateModel(
            name='ReceiveStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Message')),
            ],
            options={
                'verbose_name': 'Receive status',
                'verbose_name_plural': 'Receive statuses',
            },
        ),
        migrations.RemoveField(
            model_name='messagestatus',
            name='message',
        ),
        migrations.DeleteModel(
            name='MessageStatus',
        ),
    ]
