# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-05 09:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceiveOutOfBandStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('delivered', models.BooleanField(default=False)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Message')),
            ],
            options={
                'verbose_name_plural': 'ReceiveOutOfBand statuses',
                'verbose_name': 'ReceiveOutOfBand status',
            },
        ),
        migrations.RenameModel(
            old_name='MessageStatus',
            new_name='ReceiveStatus',
        ),
        migrations.AlterModelOptions(
            name='receivestatus',
            options={'verbose_name': 'Receive status', 'verbose_name_plural': 'Receive statuses'},
        ),
    ]
