# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-09 14:36
from __future__ import unicode_literals

from django.db import migrations, models


def migrate_golem_messages_types_from_strings_to_ints(apps, _schema_editor):

    Message = apps.get_model('core', 'Message')
    for message in Message.objects.all():
        if message.type == 'ForceReportComputedTask':
            message.tmp_type = 4001
        elif message.type == 'AckReportComputedTask':
            message.tmp_type = 4002
        elif message.type == 'RejectReportComputedTask':
            message.tmp_type = 4003
        elif message.type == 'VerdictReportComputedTask':
            message.tmp_type = 4004
        message.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180105_0945'),
    ]

    operations = [
        migrations.AddField(
            model_name  = 'message',
            name        = 'tmp_type',
            field       = models.PositiveSmallIntegerField(default=0),
        ),
        migrations.RunPython(migrate_golem_messages_types_from_strings_to_ints),
        migrations.RemoveField(
            model_name  = 'message',
            name        = 'type',
        ),
        migrations.RenameField(
            model_name  = 'message',
            old_name    = 'tmp_type',
            new_name    = 'type'
        ),
    ]
