# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-13 08:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_force_get_task_result_fix'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalTransactionState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nonce', models.DecimalField(decimal_places=0, default=0, max_digits=32, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PendingEthereumTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nonce', models.DecimalField(decimal_places=0, max_digits=78)),
                ('gasprice', models.DecimalField(decimal_places=0, max_digits=78)),
                ('startgas', models.DecimalField(decimal_places=0, max_digits=78)),
                ('value', models.DecimalField(decimal_places=0, max_digits=78)),
                ('to', models.BinaryField(max_length=20)),
                ('data', models.BinaryField()),
                ('v', models.IntegerField()),
                ('r', models.DecimalField(decimal_places=0, max_digits=78)),
                ('s', models.DecimalField(decimal_places=0, max_digits=78)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
