# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-06 23:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20180130_1413'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageAuth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_public_key', utils.fields.Base64Field(db_column='provider_public_key', max_length=64)),
                ('requestor_public_key', utils.fields.Base64Field(db_column='requestor_public_key', max_length=64)),
                ('message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='auth', to='core.Message')),
            ],
        ),
    ]
