# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-16 13:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_messageauth'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Message',
            new_name='StoredMessage',
        ),
    ]
