# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-22 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20180216_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storedmessage',
            name='task_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
