# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-29 12:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_store_message_timestamp_fix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storedmessage',
            name='subtask_id',
            field=models.CharField(max_length=36),
        ),
        migrations.AlterField(
            model_name='storedmessage',
            name='task_id',
            field=models.CharField(max_length=36),
        ),
        migrations.AlterField(
            model_name='subtask',
            name='subtask_id',
            field=models.CharField(db_index=True, max_length=36, unique=True),
        ),
        migrations.AlterField(
            model_name='subtask',
            name='task_id',
            field=models.CharField(max_length=36),
        ),
    ]
