# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-28 14:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20180918_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtask',
            name='want_to_compute_task',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='subtasks_for_want_to_compute_task', to='core.StoredMessage'),
            preserve_default=False,
        ),
    ]
