# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-15 12:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20180315_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentinfo',
            name='pending_response',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.PendingResponse'),
        ),
        migrations.AlterField(
            model_name='pendingresponse',
            name='response_type',
            field=models.CharField(choices=[('ForceReportComputedTask', 'ForceReportComputedTask'), ('ForceSubtaskResultsSettled', 'ForceSubtaskResultsSettled'), ('ForceReportComputedTaskResponse', 'ForceReportComputedTaskResponse'), ('VerdictReportComputedTask', 'VerdictReportComputedTask'), ('ForceGetTaskResult', 'ForceGetTaskResult'), ('ForceGetTaskResultRejected', 'ForceGetTaskResultRejected'), ('ForceGetTaskResultFailed', 'ForceGetTaskResultFailed'), ('ForceGetTaskResultUpload', 'ForceGetTaskResultUpload'), ('ForceGetTaskResultDownload', 'ForceGetTaskResultDownload'), ('ForceSubtaskResults', 'ForceSubtaskResults'), ('SubtaskResultsSettled', 'SubtaskResultsSettled'), ('ForceSubtaskResultsResponse', 'ForceSubtaskResultsResponse'), ('SubtaskResultsRejected', 'SubtaskResultsRejected'), ('ForcePaymentCommitted', 'ForcePaymentCommitted')], max_length=32),
        ),
    ]
