# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-23 17:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_subtask_result_upload_finished'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepositAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ethereum_address', models.CharField(max_length=42)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Client')),
            ],
        ),
        migrations.CreateModel(
            name='DepositClaim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payee_ethereum_address', models.CharField(max_length=42)),
                ('concent_use_case', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('tx_hash', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('payer_deposit_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.DepositAccount')),
                ('subtask', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Subtask')),
            ],
        ),
    ]
