# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-15 16:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20180315_1239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messageauth',
            name='message',
        ),
        migrations.RemoveField(
            model_name='receiveoutofbandstatus',
            name='message',
        ),
        migrations.RemoveField(
            model_name='receivestatus',
            name='message',
        ),
        migrations.AlterField(
            model_name='pendingresponse',
            name='response_type',
            field=models.CharField(choices=[('ForceReportComputedTask', 'ForceReportComputedTask'), ('ForceReportComputedTaskResponse', 'ForceReportComputedTaskResponse'), ('VerdictReportComputedTask', 'VerdictReportComputedTask'), ('ForceGetTaskResultRejected', 'ForceGetTaskResultRejected'), ('ForceGetTaskResultFailed', 'ForceGetTaskResultFailed'), ('ForceGetTaskResultUpload', 'ForceGetTaskResultUpload'), ('ForceGetTaskResultDownload', 'ForceGetTaskResultDownload'), ('ForceSubtaskResults', 'ForceSubtaskResults'), ('SubtaskResultsSettled', 'SubtaskResultsSettled'), ('ForceSubtaskResultsResponse', 'ForceSubtaskResultsResponse'), ('SubtaskResultsRejected', 'SubtaskResultsRejected'), ('ForcePaymentCommitted', 'ForcePaymentCommitted')], max_length=32),
        ),
        migrations.DeleteModel(
            name='MessageAuth',
        ),
        migrations.DeleteModel(
            name='ReceiveOutOfBandStatus',
        ),
        migrations.DeleteModel(
            name='ReceiveStatus',
        ),
    ]
