# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-26 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_depositaccount_depositclaim'),
    ]

    operations = [
        migrations.AddField(
            model_name='storedmessage',
            name='protocol_version',
            field=models.CharField(default='2.15.0', max_length=10),
            preserve_default=False,
        ),
    ]
