# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-09 06:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20180418_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtask',
            name='task_to_compute',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtasks_for_task_to_compute', to='core.StoredMessage'),
        ),
    ]
