# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-11-08 12:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_storedmessage_protocol_version'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='depositclaim',
            name='subtask',
        ),
    ]
