# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-10 16:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20180509_0600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentinfo',
            name='task_owner_key',
            field=models.BinaryField(),
        ),
    ]
