# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-11-08 12:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_depositclaim_subtask'),
    ]

    operations = [
        migrations.AddField(
            model_name='depositclaim',
            name='subtask_id',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='depositclaim',
            unique_together=set([('subtask_id', 'concent_use_case', 'payee_ethereum_address')]),
        ),
    ]
