# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-18 09:02
from __future__ import unicode_literals

import copy
import datetime

from django.db import migrations
from django.utils import timezone

from golem_messages import message


def remove_subtasks_without_task_to_compute_and_report_computed_task(apps, _schema_editor):

    Subtask = apps.get_model('core', 'Subtask')
    StoredMessage = apps.get_model('core', 'StoredMessage')

    for subtask in Subtask.objects.filter(report_computed_task=None):
        ack_report_computed_task = message.Message.deserialize(
            subtask.ack_report_computed_task.data.tobytes(),
            None,
            check_time=False
        )
        assert ack_report_computed_task.report_computed_task is not None

        stored_message = StoredMessage(
            type=ack_report_computed_task.report_computed_task.TYPE,
            timestamp=datetime.datetime.now(timezone.utc),
            data=copy.copy(ack_report_computed_task.report_computed_task).serialize(),
            task_id=subtask.task_id,
            subtask_id=subtask.subtask_id,
        )
        stored_message.full_clean()
        stored_message.save()

        subtask.report_computed_task = stored_message
        subtask.full_clean()
        subtask.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20180510_1635'),
    ]

    operations = [
        migrations.RunPython(
            remove_subtasks_without_task_to_compute_and_report_computed_task,
            reverse_code=migrations.RunPython.noop
        ),
    ]
