# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-11-15 12:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20181108_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depositaccount',
            name='ethereum_address',
            field=models.CharField(max_length=42, unique=True),
        ),
    ]
