# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-12-13 12:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20181115_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='depositclaim',
            name='closure_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
