# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-12-17 12:55
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_depositclaim_closure_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depositclaim',
            name='amount',
            field=models.DecimalField(decimal_places=0, max_digits=78),
        ),
        migrations.AlterField(
            model_name='paymentinfo',
            name='amount_paid',
            field=models.DecimalField(decimal_places=0, max_digits=78, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='paymentinfo',
            name='amount_pending',
            field=models.DecimalField(decimal_places=0, max_digits=78, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
