# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-12-21 11:54
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20181217_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depositaccount',
            name='ethereum_address',
            field=models.CharField(max_length=42, unique=True, validators=[django.core.validators.MinLengthValidator(42)]),
        ),
        migrations.AlterField(
            model_name='depositclaim',
            name='payee_ethereum_address',
            field=models.CharField(max_length=42, validators=[django.core.validators.MinLengthValidator(42)]),
        ),
        migrations.AlterField(
            model_name='depositclaim',
            name='tx_hash',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(64)]),
        ),
        migrations.AlterField(
            model_name='paymentinfo',
            name='provider_eth_account',
            field=models.CharField(max_length=42, validators=[django.core.validators.MinLengthValidator(42)]),
        ),
        migrations.AlterField(
            model_name='paymentinfo',
            name='task_owner_key',
            field=models.BinaryField(validators=[django.core.validators.MinLengthValidator(64), django.core.validators.MaxLengthValidator(64)]),
        ),
    ]
