# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-01-28 18:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20181221_1154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentinfo',
            name='pending_response',
        ),
        migrations.AddField(
            model_name='pendingresponse',
            name='payment_info',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.PaymentInfo'),
        ),
    ]
