# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-01-29 13:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20190128_1857'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subtask',
            unique_together=set([('requestor', 'subtask_id')]),
        ),
    ]
